In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

[2017-10-20 14:45:30,120] Making new env: FrozenLake-v0


In [3]:
# Initialize table with all zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
# create lists to contain total rewards and steps per episode
# jList = []
rList = []
for i in range(num_episodes):
    # Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j += 1
        # Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1, r, d, _ = env.step(a)
        # Update Q-Table with new knowledge
        Q[s,a] = Q[s, a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    # jList.append(j)
    rList.append(rAll)

In [4]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.5605


In [5]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  1.24800442e-01   1.32677498e-02   1.14286565e-02   1.16989190e-02]
 [  8.10976336e-04   1.57322666e-03   3.29695463e-03   2.05157710e-01]
 [  1.87151369e-03   2.71726911e-03   7.74940847e-03   3.16075738e-01]
 [  5.41059264e-03   1.72115635e-03   8.45442536e-06   9.68761267e-02]
 [  1.20784171e-01   1.78552778e-03   2.01529677e-03   2.20144971e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.85718047e-04   2.88951600e-05   3.11219568e-04   9.59671879e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.61989108e-03   4.67129344e-03   4.16795347e-04   1.74874069e-01]
 [  0.00000000e+00   7.79046615e-02   1.14197360e-03   1.75030614e-03]
 [  1.13298990e-02   7.78240000e-06   5.54176816e-04   6.11741517e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  8.85283620e-04   1.37494297e-03   5.68724390e-01   1